# Generated by Django 4.0 on 2021-12-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'techs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deploy', models.URLField()),
                ('repo', models.URLField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project_techs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tech')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'ordering': ['date'],
            },
        ),
    ]
