# Generated by Django 4.0 on 2022-01-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_techs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.technology'),
        ),
    ]
