# Generated by Django 4.0 on 2021-12-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(upload_to='app/contacts')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'educations',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'employments',
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('english', models.TextField(blank=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
                ('educations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.education')),
            ],
            options={
                'verbose_name_plural': 'cvs',
            },
        ),
    ]
