# Generated by Django 4.0 on 2022-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_project_techs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTechnology',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['years'], 'verbose_name_plural': 'educations'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.AddField(
            model_name='education',
            name='years',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='period',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(blank=True, upload_to='app/technologies'),
        ),
    ]
