# Generated by Django 4.0 on 2022-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_projecttechnology_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='contacts',
        ),
        migrations.AddField(
            model_name='cv',
            name='contacts',
            field=models.ManyToManyField(to='app.Contact'),
        ),
        migrations.RemoveField(
            model_name='cv',
            name='educations',
        ),
        migrations.AddField(
            model_name='cv',
            name='educations',
            field=models.ManyToManyField(to='app.Education'),
        ),
        migrations.RemoveField(
            model_name='cv',
            name='projects',
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.ManyToManyField(to='app.Project'),
        ),
        migrations.RemoveField(
            model_name='cv',
            name='technologies',
        ),
        migrations.AddField(
            model_name='cv',
            name='technologies',
            field=models.ManyToManyField(to='app.Technology'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_techs',
        ),
        migrations.AddField(
            model_name='project',
            name='project_techs',
            field=models.ManyToManyField(to='app.Technology'),
        ),
    ]
