# Generated by Django 4.0 on 2022-01-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cv_contacts_cv_contacts_remove_cv_educations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['education_years'], 'verbose_name_plural': 'educations'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_date'], 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['technology_name'], 'verbose_name_plural': 'technologies'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='icon',
            new_name='contact_icon',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='link',
            new_name='contact_link',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='place',
            new_name='education_place',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='speciality',
            new_name='education_speciality',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='years',
            new_name='education_years',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='desc',
            new_name='employment_desc',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='period',
            new_name='employment_period',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='place',
            new_name='employment_place',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='project_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deploy',
            new_name='project_deploy',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='repo',
            new_name='project_repo',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='logo',
            new_name='technology_logo',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='name',
            new_name='technology_name',
        ),
    ]
