# Generated by Django 4.0 on 2022-01-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_education_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_icon',
            field=models.ImageField(upload_to='static/contacts'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology_logo',
            field=models.ImageField(blank=True, upload_to='static/technologies'),
        ),
    ]
