# Generated by Django 4.0 on 2022-01-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_technology_technology_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['years'], 'verbose_name_plural': 'educations'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date'], 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name_plural': 'technologies'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='education_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='education_speciality',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='education_years',
            new_name='years',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='employment_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='employment_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='employment_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_deploy',
            new_name='deploy',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_repo',
            new_name='repo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_techs',
            new_name='techs',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='technology_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='technology_name',
            new_name='name',
        ),
    ]
