# Generated by Django 4.0 on 2022-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_education_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.ImageField(upload_to='app/static/contacts'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(upload_to='app/static/technologies'),
        ),
    ]
