# Generated by Django 4.0 on 2022-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contact_icon_alter_technology_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.ImageField(upload_to='static/contacts'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(upload_to='static/technologies'),
        ),
    ]
