# Generated by Django 4.0 on 2022-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_contact_icon_alter_technology_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
